package docs
package main

// 这是一个示例文件，展示如何在应用中集成反思系统
// 请根据你的具体应用情况修改和使用



































































































































}	logger.Infof("✅ Trader %s unregistered", traderID)	scheduler.UnregisterTrader(traderID)	logger.Infof("➖ Unregistering trader %s from reflection", traderID)func UnregisterTraderExample(scheduler *backtest.ReflectionScheduler, traderID string) {// UnregisterTraderExample 注销交易员反思的例子}	logger.Infof("✅ Trader %s registered", traderID)	scheduler.RegisterTrader(traderID)	logger.Infof("➕ Registering new trader %s for reflection", traderID)func RegisterNewTraderExample(scheduler *backtest.ReflectionScheduler, traderID string) {// RegisterNewTraderExample 注册新交易员进行反思的例子}	return nil	}			r.TotalTrades)			r.SuccessRate*100,			r.ReflectionTime.Format("2006-01-02"),		logger.Infof("  - %s: %.2f%% success rate, %d trades",	for _, r := range reflections {	logger.Infof("✅ Found %d reflections", len(reflections))	}		return err		logger.Errorf("❌ Failed to get reflections: %v", err)	if err != nil {	reflections, err := scheduler.GetRecentReflections(traderID, 10)	logger.Infof("📊 Getting reflection history for trader %s", traderID)func GetReflectionHistoryExample(scheduler *backtest.ReflectionScheduler, traderID string) error {// GetReflectionHistoryExample 获取反思历史的例子}	return nil	logger.Infof("✅ Reflection completed for trader %s", traderID)	}		return err		logger.Errorf("❌ Failed to trigger reflection: %v", err)	if err := scheduler.ManualTrigger(traderID); err != nil {	logger.Infof("🚀 Manually triggering reflection for trader %s", traderID)func ManualTriggerExample(scheduler *backtest.ReflectionScheduler, traderID string) error {// ManualTriggerExample 手动触发反思的例子*/}	defer reflectionScheduler.Stop()	// 优雅关闭	// ... 启动应用 ...	reflectionHandlers.RegisterReflectionRoutes(router)	reflectionHandlers := api.NewReflectionHandlers(reflectionScheduler, db)	// 注册反思 API 路由	// ... 启动 HTTP 服务器 ...	}		panic(err)	if err != nil {	reflectionScheduler, err := initReflectionSystem(db, aiClient, traderIDs)	// 初始化反思系统	}		traderIDs[i] = t.ID	for i, t := range traders {	traderIDs := make([]string, len(traders))	traders, _ := db.Trader().List("user_id")	// 获取所有活跃交易员	aiClient := mcp.NewDeepSeekClient("your-api-key", "")	// 初始化 AI 客户端	}		panic(err)	if err != nil {	db, err := store.New("trading.db")	// 初始化数据库	// ... 其他初始化代码 ...func main() {/*// Example usage in main():}	return reflectionScheduler, nil	logger.Infof("✅ Reflection system initialized successfully")	}		return nil, err		logger.Errorf("❌ Failed to start reflection scheduler: %v", err)	if err := reflectionScheduler.Start(); err != nil {	// 5. 启动调度器	}		logger.Infof("📝 Trader %s registered for reflection", traderID)		reflectionScheduler.RegisterTrader(traderID)	for _, traderID := range traders {	// 4. 注册交易员	reflectionScheduler.SetSchedule("0 22 * * 0") // 每周日 22:00	reflectionScheduler.SetAnalysisDays(7)         // 分析 7 天的交易	// 3. 配置调度器（可选）	reflectionScheduler := backtest.NewReflectionScheduler(reflectionEngine, db)	// 2. 创建反思调度器	logger.Infof("✅ Reflection engine created")	reflectionEngine := backtest.NewReflectionEngine(aiClient, db)	// 1. 创建反思引擎	logger.Infof("🔧 Initializing reflection system...")) (*backtest.ReflectionScheduler, error) {	traders []string,	aiClient mcp.AIClient,	db *store.Store,func initReflectionSystem(// 在应用启动时调用此函数// initReflectionSystem 初始化反思系统)	"nofx/store"	"nofx/mcp"	"nofx/logger"	"nofx/backtest"import (